# Generated by Django 5.0.2 on 2024-03-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='fetured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
