# Generated by Django 5.0.2 on 2024-03-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0002_alter_menuitem_fetured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
